workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      node: 22
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web
        script: npx vite build
      - name: Add iOS platform
        script: |
          npx cap add ios || true
          npx cap sync ios
      - name: Install CocoaPods
        script: cd ios/App && pod install
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "com.cozza.casa" --type ios_app_store --create
      - name: Set up keychain
        script: keychain initialize
      - name: Add certs to keychain
        script: keychain add-certificates
      - name: Use profiles
        script: xcode-project use-profiles
      - name: Build IPA
        script: |
          xcode-project build-ipa --workspace "ios/App/App.xcworkspace" --scheme "App"
    artifacts:
      - build/ios/ipa/*.ipa